production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/juliet_dev
    log_level: DEBUG

qa:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO


test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
