#!/bin/tcsh 
rake 'data:file[publisher,  data/publishers]'
rake 'data:file[journal,    data/journals.elsevier,         Elsevier]'
rake 'data:file[journal,    data/journals.wiley,            John Wiley and Sons]'
rake 'data:file[journal,    data/journals.ams,              American Mathematical Society]'
rake 'data:file[journal,    data/journals.taylorfrancis,    Taylor & Francis]'
